[versions]
assertj = "3.27.6"
bouncycastle = "1.82"
caffeine = "3.2.3"
commonsLang = "3.19.0"
commonsText = "1.14.0"
hivemq-extensionSdk = "4.4.0"
jaxb-api = "2.3.3"
jaxb-impl = "2.3.9"
jcommander = "1.82"
jetbrains-annotations = "26.0.2-1"
junit-jupiter = "5.10.0"
mockito = "5.20.0"

[libraries]
assertj = { module = "org.assertj:assertj-core", version.ref = "assertj" }
bouncycastle-prov = { module = "org.bouncycastle:bcprov-jdk18on", version.ref = "bouncycastle" }
caffeine = { module = "com.github.ben-manes.caffeine:caffeine", version.ref = "caffeine" }
commonsLang = { module = "org.apache.commons:commons-lang3", version.ref = "commonsLang" }
commonsText = { module = "org.apache.commons:commons-text", version.ref = "commonsText" }
jaxb-api = { module = "jakarta.xml.bind:jakarta.xml.bind-api", version.ref = "jaxb-api" }
jaxb-impl = { module = "com.sun.xml.bind:jaxb-impl", version.ref = "jaxb-impl" }
jcommander = { module = "com.beust:jcommander", version.ref = "jcommander" }
jetbrains-annotations = { module = "org.jetbrains:annotations", version.ref = "jetbrains-annotations" }
mockito = { module = "org.mockito:mockito-core", version.ref = "mockito" }

[plugins]
defaults = { id = "io.github.sgtsilvio.gradle.defaults", version = "0.2.0" }
hivemq-extension = { id = "com.hivemq.extension", version = "4.0.0" }
license = { id = "com.github.hierynomus.license", version = "0.16.1" }
oci = { id = "io.github.sgtsilvio.gradle.oci", version = "0.24.0" }
